source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JDFTableData_Example', :exclusive => true do
  pod "JDFTableData", :path => "../"
end

target 'JDFTableData_Tests', :exclusive => true do
  pod "JDFTableData", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
